import { useState } from "react";
import { ChevronRight, Download, RefreshCw, Eye, ExternalLink } from "lucide-react";
import { toast } from "sonner";
import { Link } from "@tanstack/react-router";
import type { BidDocument } from "@/lib/doc-queries";
import { useReindexDocument } from "@/lib/doc-queries";
import type { Bid } from "@/lib/bid-queries";
import { supabase } from "@/integrations/supabase/client";

const EXT_STYLE: Record<string, { bg: string; color: string; label: string }> = {
  pdf:  { bg: "rgba(239,68,68,0.12)",  color: "#ef4444", label: "PDF" },
  docx: { bg: "rgba(59,130,246,0.12)", color: "#3b82f6", label: "DOC" },
  xlsx: { bg: "rgba(16,185,129,0.12)", color: "#10b981", label: "XLS" },
};

function fmtBytes(n: number) {
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(0)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}

function fmtDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric" });
}

async function downloadDoc(doc: BidDocument) {
  try {
    const { data, error } = await supabase.storage
      .from("bid-documents")
      .createSignedUrl(doc.storage_path, 120);
    if (error || !data?.signedUrl) throw error ?? new Error("No URL");
    const a = document.createElement("a");
    a.href = data.signedUrl;
    a.download = doc.name;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  } catch {
    toast.error("Download failed — please try again");
  }
}

type DocRowProps = {
  doc: BidDocument;
  onPreview: (d: BidDocument) => void;
  onReindex: (d: BidDocument) => void;
};

function DocRow({ doc, onPreview, onReindex }: DocRowProps) {
  const ext = doc.name.split(".").pop()?.toLowerCase() ?? "pdf";
  const style = EXT_STYLE[ext] ?? EXT_STYLE.pdf;
  const isGenerated = doc.source === "generated";
  const isIndexed = doc.embedding !== null;

  return (
    <div className="flex items-center gap-2.5 py-2 border-b hairline border-border last:border-0">
      <div
        className="w-7 h-7 rounded flex items-center justify-center text-[9px] font-black shrink-0"
        style={{ background: style.bg, color: style.color }}
      >
        {style.label}
      </div>

      <div className="flex-1 min-w-0">
        <div className="text-[11px] font-medium truncate">{doc.name}</div>
        <div className="text-[10px] text-muted-foreground">
          {fmtBytes(doc.size_bytes)} · {fmtDate(doc.created_at)}
          {isGenerated ? " · Generated by AI" : ""}
        </div>
      </div>

      {/* Source + index status */}
      <div className="flex items-center gap-2 shrink-0">
        {isGenerated ? (
          <span className="text-[9px] font-medium px-1.5 py-0.5 rounded bg-[#fff0e8] text-orange-600 dark:bg-orange-500/15 dark:text-orange-400">
            ✦ AI output
          </span>
        ) : (
          <span className="text-[9px] font-medium px-1.5 py-0.5 rounded bg-[#ede9fd] text-primary dark:bg-primary/15">
            ↑ Uploaded
          </span>
        )}
        <div className="flex items-center gap-1">
          <div
            className={`w-1.5 h-1.5 rounded-full ${
              isIndexed ? "bg-green-500" : "bg-muted-foreground/40"
            }`}
          />
          <span
            className={`text-[9px] ${
              isIndexed ? "text-green-600 dark:text-green-400" : "text-muted-foreground"
            }`}
          >
            {isIndexed ? "Indexed" : isGenerated ? "Not indexed" : "Indexing…"}
          </span>
        </div>
      </div>

      {/* Actions: preview, download, re-index or index */}
      <div className="flex items-center gap-1 shrink-0">
        <button
          onClick={() => onPreview(doc)}
          title="Preview"
          className="w-6 h-6 flex items-center justify-center rounded border hairline border-border text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
        >
          <Eye className="w-3 h-3" />
        </button>
        <button
          onClick={() => downloadDoc(doc)}
          title="Download"
          className="w-6 h-6 flex items-center justify-center rounded border hairline border-border text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
        >
          <Download className="w-3 h-3" />
        </button>
        {isIndexed ? (
          <button
            onClick={() => onReindex(doc)}
            title="Re-index"
            className="w-6 h-6 flex items-center justify-center rounded border hairline border-border text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
          >
            <RefreshCw className="w-3 h-3" />
          </button>
        ) : isGenerated ? (
          <button
            onClick={() => onReindex(doc)}
            title="Index this document"
            className="h-6 px-2 text-[9px] font-semibold rounded bg-[#ede9fd] text-primary border hairline border-primary/20 hover:bg-primary/25 transition-colors dark:bg-primary/15 dark:border-primary/30"
          >
            → Index
          </button>
        ) : null}
      </div>
    </div>
  );
}

type Props = {
  bids: Bid[];
  docs: BidDocument[];
  isLoading: boolean;
  onPreview: (doc: BidDocument) => void;
};

export function BidDocumentsTab({ bids, docs, isLoading, onPreview }: Props) {
  const [query, setQuery] = useState("");
  const [openFolders, setOpenFolders] = useState<Set<string>>(new Set());
  const reindex = useReindexDocument();

  const bidDocs = docs.filter((d) => d.bid_id !== null);

  const docsByBid = bidDocs.reduce<Record<string, BidDocument[]>>((acc, doc) => {
    const key = doc.bid_id!;
    (acc[key] ??= []).push(doc);
    return acc;
  }, {});

  const totalIndexed = bidDocs.filter((d) => d.embedding !== null).length;
  const totalAiNotIndexed = bidDocs.filter(
    (d) => d.source === "generated" && d.embedding === null
  ).length;

  const filteredBids = bids.filter((bid) => {
    if (!query) return true;
    const q = query.toLowerCase();
    return (
      bid.client_name.toLowerCase().includes(q) ||
      bid.title.toLowerCase().includes(q)
    );
  });

  function toggle(bidId: string) {
    setOpenFolders((prev) => {
      const next = new Set(prev);
      next.has(bidId) ? next.delete(bidId) : next.add(bidId);
      return next;
    });
  }

  function handleReindex(doc: BidDocument) {
    reindex.mutate(doc.id, {
      onSuccess: () => toast.success("Re-indexing started…"),
      onError: () => toast.error("Re-index failed"),
    });
  }

  if (isLoading) {
    return (
      <div className="flex-1 flex items-center justify-center text-[12px] text-muted-foreground">
        Loading…
      </div>
    );
  }

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      {/* Stats strip */}
      <div className="flex items-center gap-5 px-5 py-2 border-b hairline border-border bg-card shrink-0">
        <div className="flex items-baseline gap-1">
          <span className="text-[13px] font-semibold tabular-nums">{bids.length}</span>
          <span className="text-[10px] text-muted-foreground">bid folders</span>
        </div>
        <div className="w-px h-3.5 bg-border" />
        <div className="flex items-baseline gap-1">
          <span className="text-[13px] font-semibold tabular-nums">{bidDocs.length}</span>
          <span className="text-[10px] text-muted-foreground">documents</span>
        </div>
        <div className="w-px h-3.5 bg-border" />
        <div className="flex items-baseline gap-1">
          <span className="text-[13px] font-semibold tabular-nums text-green-600 dark:text-green-400">
            {totalIndexed}
          </span>
          <span className="text-[10px] text-muted-foreground">indexed</span>
        </div>
        {totalAiNotIndexed > 0 && (
          <>
            <div className="w-px h-3.5 bg-border" />
            <div className="flex items-baseline gap-1">
              <span className="text-[13px] font-semibold tabular-nums text-orange-500">
                {totalAiNotIndexed}
              </span>
              <span className="text-[10px] text-muted-foreground">AI output (not indexed)</span>
            </div>
          </>
        )}
      </div>

      {/* Search bar */}
      <div className="flex items-center gap-3 px-5 py-2 border-b hairline border-border shrink-0">
        <div className="relative flex items-center flex-1 max-w-xs">
          <span className="absolute left-2.5 text-muted-foreground text-[11px] pointer-events-none select-none">
            ⌕
          </span>
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            className="w-full h-7 bg-background border hairline border-border rounded-md pl-7 pr-3 text-[11px] text-foreground outline-none focus:ring-1 focus:ring-primary/50 placeholder:text-muted-foreground"
            placeholder="Search bid folders…"
          />
        </div>
        <span className="text-[10px] text-muted-foreground ml-auto tabular-nums">
          {filteredBids.length} bid{filteredBids.length !== 1 ? "s" : ""}
        </span>
      </div>

      {/* Folder list */}
      <div className="flex-1 overflow-y-auto">
        {filteredBids.length === 0 ? (
          <div className="flex flex-col items-center justify-center gap-2 py-16 text-muted-foreground">
            <div className="text-3xl opacity-20">📁</div>
            <div className="text-[12px]">No bids match your search</div>
          </div>
        ) : (
          filteredBids.map((bid) => {
            const folderDocs = docsByBid[bid.id] ?? [];
            const isOpen = openFolders.has(bid.id);

            return (
              <div key={bid.id} className="border-b hairline border-border">
                <button
                  onClick={() => toggle(bid.id)}
                  className="w-full flex items-center gap-2.5 px-5 py-2.5 hover:bg-muted/30 transition-colors text-left"
                >
                  <ChevronRight
                    className={`w-3 h-3 text-muted-foreground shrink-0 transition-transform duration-150 ${
                      isOpen ? "rotate-90" : ""
                    }`}
                  />
                  <span className="text-[13px] shrink-0 select-none">
                    {isOpen ? "📂" : "📁"}
                  </span>
                  <div className="flex-1 min-w-0">
                    <div className="text-[12px] font-medium">{bid.client_name}</div>
                    <div className="text-[10px] text-muted-foreground mt-0.5">
                      {bid.title}
                      {" · "}
                      {folderDocs.length > 0
                        ? `${folderDocs.length} doc${folderDocs.length !== 1 ? "s" : ""} · Updated ${fmtDate(bid.updated_at)}`
                        : `No documents · Created ${fmtDate(bid.created_at)}`}
                    </div>
                  </div>
                  <div className="flex items-center gap-2 shrink-0">
                    <span className="text-[10px] text-muted-foreground tabular-nums">
                      {folderDocs.length > 0
                        ? `${folderDocs.length} doc${folderDocs.length !== 1 ? "s" : ""}`
                        : "empty"}
                    </span>
                    <Link
                      to="/bids/$id"
                      params={{ id: bid.id }}
                      onClick={(e) => e.stopPropagation()}
                      className="w-6 h-6 flex items-center justify-center rounded border hairline border-border text-muted-foreground hover:bg-muted hover:text-foreground transition-colors"
                      title="Open bid"
                    >
                      <ExternalLink className="w-3 h-3" />
                    </Link>
                  </div>
                </button>

                {isOpen && (
                  <div className="bg-muted/20 px-5 pt-1 pb-2 pl-[52px]">
                    {folderDocs.length === 0 ? (
                      <div className="py-4 flex flex-col gap-1">
                        <div className="text-[11px] text-muted-foreground">
                          No documents yet. This folder is auto-created when a bid is added.
                        </div>
                        <div className="text-[10px] text-muted-foreground/60">
                          Documents appear here when uploaded during bid intake or pinned in AI chat.
                        </div>
                      </div>
                    ) : (
                      folderDocs.map((doc) => (
                        <DocRow
                          key={doc.id}
                          doc={doc}
                          onPreview={onPreview}
                          onReindex={handleReindex}
                        />
                      ))
                    )}
                  </div>
                )}
              </div>
            );
          })
        )}
      </div>
    </div>
  );
}
